### ISSUE TITLE
jakarta email package

### ISSUE THREAD

**Issue by sdelamo** [openrewrite/rewrite-micronaut#71]
Micronaut Email 2 migrates to [Jakarta Mail](https://jakartaee.github.io/mail-api/) package namespaces, from `javax.mail` to `jakarta.mail`. 

| Javax annotations                   | Jakarta annotations                   |
| ----------------------------------- | ------------------------------------- |
| `javax.mail.Message`                  | `jakarta.mail.Message`                  |
| `javax.mail.MessagingException`       | `jakarta.mail.MessagingException`       |
| `javax.mail.Flags`                    |  `jakarta.mail.Flags`                    |
| `javax.mail.Folder`                   |  `jakarta.mail.Folder`                   |
| `javax.mail.Session`                  | `jakarta.mail.Session`                  |
| `javax.mail.Store`                    |  `jakarta.mail.Store`                    |
| `javax.mail.internet.MimeMessage`     | `jakarta.mail.internet.MimeMessage`     |
| `javax.mail.internet.MimeMultipart`   | `jakarta.mail.internet.MimeMultipart`   |
| `javax.mail.util.ByteArrayDataSource` | `jakarta.mail.util.ByteArrayDataSource` |
| `javax.mail.Authenticator`            | `jakarta.mail.Authenticator`            |
| `javax.mail.PasswordAuthentication`   | `jakarta.mail.PasswordAuthentication`   |

We need a recipe to update this.

**Comment by jeremyg484** [comment]
@sdelamo I believe we already have this covered - see https://github.com/openrewrite/rewrite-micronaut/blob/42adb32973587d9b4a7a3ff1ad16e0a4303a3760/src/main/resources/META-INF/rewrite/micronaut3-to-4.yml#L160

**Comment by timtebeek** [comment]
This first one is also covered by a unit test
https://github.com/openrewrite/rewrite-micronaut/blob/e61798481407b9a86869defee73b00a835f3c3fd/src/test/java/org/openrewrite/java/micronaut/UpdateMicronautEmailTest.java#L53-L56

And since the recipe implementation uses a recursive package change
https://github.com/openrewrite/rewrite-micronaut/blob/42adb32973587d9b4a7a3ff1ad16e0a4303a3760/src/main/resources/META-INF/rewrite/micronaut3-to-4.yml#L163-L167

I'd then think this has been sufficiently covered to close the issue, but I'll leave that up to you. I'm merely providing context.

**Comment by jeremyg484** [comment]
Closing because this had already been implemented previously.
